# Generated by Django 5.0.4 on 2024-05-01 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=120, verbose_name='Food')),
                ('date', models.DateField(verbose_name='Date Eaten')),
                ('calories', models.IntegerField(verbose_name='Calories')),
                ('totalFat', models.IntegerField(verbose_name='Total Fat')),
                ('saturatedFat', models.IntegerField(verbose_name='Saturated Fat')),
                ('transFat', models.IntegerField(verbose_name='Trans Fat')),
                ('sodium', models.IntegerField(verbose_name='Sodium')),
                ('totalCarb', models.IntegerField(verbose_name='Total Carbohydrates')),
                ('addedSugars', models.IntegerField(verbose_name='Added Sugar')),
                ('protein', models.IntegerField(verbose_name='Protein')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('eaten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontend.serving')),
            ],
        ),
    ]
