# Generated by Django 5.0.4 on 2024-05-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serving',
            name='addedSugars',
            field=models.FloatField(verbose_name='Added Sugar'),
        ),
        migrations.AlterField(
            model_name='serving',
            name='protein',
            field=models.FloatField(verbose_name='Protein'),
        ),
        migrations.AlterField(
            model_name='serving',
            name='saturatedFat',
            field=models.FloatField(verbose_name='Saturated Fat'),
        ),
        migrations.AlterField(
            model_name='serving',
            name='sodium',
            field=models.FloatField(verbose_name='Sodium'),
        ),
        migrations.AlterField(
            model_name='serving',
            name='totalCarb',
            field=models.FloatField(verbose_name='Total Carbohydrates'),
        ),
        migrations.AlterField(
            model_name='serving',
            name='totalFat',
            field=models.FloatField(verbose_name='Total Fat'),
        ),
        migrations.AlterField(
            model_name='serving',
            name='transFat',
            field=models.FloatField(verbose_name='Trans Fat'),
        ),
    ]
