# Generated by Django 5.0.4 on 2024-05-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_rename_food_serving_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionuser',
            name='eaten',
        ),
        migrations.AddField(
            model_name='nutritionuser',
            name='eaten',
            field=models.ManyToManyField(blank=True, to='Frontend.serving'),
        ),
    ]
