# Generated by Django 5.0.4 on 2024-05-01 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_remove_nutritionuser_eaten_nutritionuser_eaten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serving',
            name='date',
        ),
    ]
