# Generated by Django 5.0.4 on 2024-05-01 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_remove_serving_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionuser',
            name='eaten',
        ),
        migrations.CreateModel(
            name='DateEaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateField(verbose_name='Date')),
                ('eaten', models.ManyToManyField(blank=True, to='Frontend.serving')),
            ],
        ),
        migrations.AddField(
            model_name='nutritionuser',
            name='totalFood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontend.dateeaten'),
        ),
    ]
